### ISSUE TITLE
FAILED TO GET VENDOR OTA

### ISSUE THREAD

**Issue by lentas1** [Kethen/waydroid_build#1]
read title

**Comment by lentas1** [comment]
device is s7

**Comment by Kethen** [comment]
read the instructions on the release, you should not get that error if you have installed the images properly and your ut is up to date

the error comes from waydroid not being able to find the local images and official halium 11 images are not yet available on their image server

**Comment by lentas1** [comment]
i still get same result

**Comment by lentas1** [comment]
trust me

**Comment by Kethen** [comment]
@lentas1 

Make sure the images are installed as `.img` and not `.sfs`, and you need to be on the latest ut for s7 before installing waydroid

<img src="https://user-images.githubusercontent.com/22017945/196057720-5283da7f-45f9-4d18-8669-49a4662af5ac.png" width=200>

<img src="https://user-images.githubusercontent.com/22017945/196057940-fd90238c-d2df-4c6a-a43e-c2a1fe4dd9bd.png" width=200>

**Comment by lentas1** [comment]
im stuck at app loading

**Comment by lentas1** [comment]
my img is in .img  format, not sfs

**Comment by lentas1** [comment]
fu**, im getting an old error with newest version ,when i tried again

**Comment by lentas1** [comment]
same than title

**Comment by lentas1** [comment]
![WIN_20221020_12_36_27_Pro](https://user-images.githubusercontent.com/88710364/196913289-754f3511-7c02-405a-a93e-609de28e8f3f.jpg)

**Comment by lentas1** [comment]
when i start i get "xdg session is not wayland"

**Comment by lentas1** [comment]
i start using root and with this command: waydroid session start

**Comment by Kethen** [comment]
@lentas1 
if waydroid get stuck loading, it's very likely that you ignored part of the instructions

`/etc/gbinder.d/anbox.conf` has to be the same as https://gitlab.com/ubports/porting/community-ports/android11/samsung-galaxy-s7/samsung-exynos8890/-/blob/main/overlay_template/system/rootfs_overlay/etc/gbinder.d/anbox.conf, with `aidl3` instead of `aidl2`
![image](https://user-images.githubusercontent.com/22017945/196979619-0e3a1185-03be-432c-a7df-9cc5ebd70c26.png)

`xdg session is not wayland` warning can be safely ignored, it came from https://github.com/waydroid/waydroid/blob/6b89a1c8228b95d8b61afdf5c67212e6a9bc35e3/tools/actions/session_manager.py#L18

**Comment by lentas1** [comment]
it works when i reinstalled ubuntu touch

**Comment by lentas1** [comment]
i now got big error: importerror from python code
